### ISSUE TITLE
Minutes Meeting 2018-08-15

### ISSUE THREAD

**Issue by Patechoc** [DataForGood-Norway/season-01#2]
Based on [this draft](https://docs.google.com/document/d/1bs3oRgGD9FOuVdqHFqF-Qi-QFUD-29-9TGCYWuwQ7SQ/edit), we started planning the first season:

* a 3-months session starting with a **Kick-off meeting** on **September 11th 2018** (Tuesday)
* finishing with a **Final demo day** on **November 27th**
* we agreed to stick to Tuesdays (the working space still need to be confirmed)
* **Workshop 1**: Defining project's details, as early as **September 18th**
* **Workshop 2**: mini-hands on on project management tools (Trello, Github, ...) on **September 25**
* we will have teams of mentors following the projects after every 2-weeks sprint. Possibly leading to additional technical workshops if needed.

The few tasks we talked about have been written [as issues in this same repo](https://github.com/DataForGood-Norway/season-01/issues). 

We can now:

* share data on Google Drive in [this folder](https://drive.google.com/open?id=15E7e6DE3c7n9-4qQGXmO2OayYZQ0zzx_)
* share events on Google Calendar following these instructions: https://github.com/DataForGood-Norway/season-01/issues/5

The action points for the next meeting is just to write the text advertising the session, and we will start adding tasks and distribute them among us at the **next meeting: Tuesday, august 22nd at 5:30pm, pub of Socentral, Oslo**

**Comment by ankhek** [comment]
Hi! just noticed that the I can't add any new item, e.g. docs, sheets etc to the folder or making a new folder.. (I don't have access to the season 1 folder either.) Is it because how I signed in to google?..

**Comment by Patechoc** [comment]
The GFolder wasn't shared properly with edit permissions. It is fixed now in case you experienced the same problem.
